CREATE DATABASE rental_data;
USE rental_data;
CREATE TABLE `rental_data`.`RENTAL_DATA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `BEDROOM_COUNT` INT NOT NULL,
  `BATHROOM_COUNT` INT NOT NULL,
  `SQUARE_FEET` INT NOT NULL,
  `PRICE` INT NOT NULL,
  PRIMARY KEY (`ID`));