CREATE DATABASE rental_data;
USE rental_data;
CREATE TABLE `rental_data` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `BEDROOM_COUNT` int(11) NOT NULL,
  `BATHROOM_COUNT` int(11) NOT NULL,
  `SQUARE_FEET` int(11) NOT NULL,
  `PRICE` int(11) NOT NULL,
  `PRICE_PER_SQFT` double NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=7993 DEFAULT CHARSET=latin1;

CREATE TABLE `rental_data`.`coefficients` (
  `BEDROOM_COEF` DOUBLE NOT NULL,
  `BATHROOM_COEF` DOUBLE NOT NULL,
  `SQUARE_FEET_COEF` DOUBLE NOT NULL,
  `INTERCEPT` DOUBLE NOT NULL);